"""empty message

Revision ID: 649674471e6b
Revises: a6baaf70b3c8
Create Date: 2025-07-08 14:49:16.694603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649674471e6b'
down_revision: Union[str, Sequence[str], None] = 'a6baaf70b3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_instance_relations',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['repeat_entities.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'entity_id', 'instance_id')
    )
    op.create_table('repeat_entity_instances',
    sa.Column('entity_type', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_type'], ['repeat_entities.id'], ),
    sa.PrimaryKeyConstraint('entity_type', 'instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repeat_entity_instances')
    op.drop_table('group_instance_relations')
    op.drop_table('groups')
    # ### end Alembic commands ###
