"""empty message

Revision ID: a6baaf70b3c8
Revises: 
Create Date: 2025-07-07 12:17:34.337353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6baaf70b3c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learn_statuses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repeat_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repeat_relations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=True),
    sa.Column('last_repeated', sa.TIMESTAMP(), nullable=True),
    sa.Column('forgot_times', sa.Integer(), nullable=True),
    sa.Column('learn_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_type'], ['repeat_entities.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entity_type', 'entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repeat_relations')
    op.drop_table('repeat_entities')
    op.drop_table('learn_statuses')
    # ### end Alembic commands ###
