"""empty message

Revision ID: db06c251e35f
Revises: 649674471e6b
Create Date: 2025-07-16 10:13:37.954774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db06c251e35f'
down_revision: Union[str, Sequence[str], None] = '649674471e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'repeat_entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'entity_id')
    # ### end Alembic commands ###
